@extends('layouts.admin')

@section('title', 'Reports')

@section('content')
<div class="">

    <div class="content">
        <!-- Report Generation Options -->
        <div class="row mb-4">
            <div class="col-12">
                <div class="card mb-3">
                    <div class="card-body shadow">
                        <div class="d-flex justify-content-between">
                            <div class="">
                                <h5>Reports</h5>
                            </div>
                            <div class="">
                                <!-- Right-side notification and icons -->
                                <div class="col-auto nav-right">
                                    <button class="icon-btn">
                                        <i class="fas fa-bell"></i>
                                    </button>
                                    <button class="icon-btn">
                                        <i class="fas fa-envelope"></i>
                                    </button>
                                    <button class="icon-btn">
                                        <i class="fas fa-user-circle"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <p>Generate and view reports here.</p>

                <form action="{{ url('admin/reports/generate') }}" method="GET">
                    <div class="row align-items-center">
                        <div class="col-4">
                            <div class="form-group">
                                <label for="reportType" class=" mb-2">Select Report Type:</label>
                                <select class="form-control" id="reportType" name="reportType">
                                    <option value="revenue">Revenue Report</option>
                                    <option value="bookings">Bookings Report</option>
                                    <option value="customer">Customer Report</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-group">
                                <label for="dateRange" class=" mb-2">Select Date Range:</label>
                                <input type="date" class="form-control" id="startDate" name="startDate"
                                    placeholder="Start Date">

                            </div>
                        </div>
                        <div class="col-4">
                            <label for="dateRange" class="">Select Date Range:</label>

                            <input type="date" class="form-control mt-2" id="endDate" name="endDate"
                                placeholder="End Date">
                        </div>
                    </div>


                    <div class="text-end">
                        <button type="submit" class="btn btn-primary mt-3">Generate Report</button>
                    </div>
                </form>
            </div>
        </div>

        <!-- Dummy Report Data -->
        <h3>Recent Reports</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Report ID</th>
                    <th>Report Type</th>
                    <th>Date Range</th>
                    <th>Generated By</th>
                    <th>Generated On</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Revenue Report</td>
                    <td>2024-10-01 to 2024-10-14</td>
                    <td>Admin User</td>
                    <td>2024-10-14</td>
                    <td>
                        <a href="{{ url('admin/reports/view/1') }}" class="btn btn-info btn-sm">View</a>
                        <a href="{{ url('admin/reports/download/1') }}" class="btn btn-success btn-sm">Download</a>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Bookings Report</td>
                    <td>2024-09-01 to 2024-09-30</td>
                    <td>John Doe</td>
                    <td>2024-10-01</td>
                    <td>
                        <a href="{{ url('admin/reports/view/2') }}" class="btn btn-info btn-sm">View</a>
                        <a href="{{ url('admin/reports/download/2') }}" class="btn btn-success btn-sm">Download</a>
                    </td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Customer Report</td>
                    <td>2024-08-01 to 2024-08-31</td>
                    <td>Jane Smith</td>
                    <td>2024-09-01</td>
                    <td>
                        <a href="{{ url('admin/reports/view/3') }}" class="btn btn-info btn-sm">View</a>
                        <a href="{{ url('admin/reports/download/3') }}" class="btn btn-success btn-sm">Download</a>
                    </td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>Revenue Report</td>
                    <td>2024-07-01 to 2024-07-31</td>
                    <td>Michael Johnson</td>
                    <td>2024-08-01</td>
                    <td>
                        <a href="{{ url('admin/reports/view/4') }}" class="btn btn-info btn-sm">View</a>
                        <a href="{{ url('admin/reports/download/4') }}" class="btn btn-success btn-sm">Download</a>
                    </td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>Bookings Report</td>
                    <td>2024-06-01 to 2024-06-30</td>
                    <td>Emily Davis</td>
                    <td>2024-07-01</td>
                    <td>
                        <a href="{{ url('admin/reports/view/5') }}" class="btn btn-info btn-sm">View</a>
                        <a href="{{ url('admin/reports/download/5') }}" class="btn btn-success btn-sm">Download</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
@endsection